site_title = "MyArxiv"
limit_days = 7
cache_url = "https://2019zhou.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning 1"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[[sources]]
limit = 150
category = "stat.ML"
title = "Machine Learning 2"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
